[env:upesy_wroom]
; Use the community-maintained platform that supports Arduino Core 3.0+
platform = espressif32
board = upesy_wroom
framework = arduino

lib_deps =
    https://github.com/knolleary/pubsubclient
    https://github.com/arduino-libraries/Ethernet
    https://github.com/bblanchon/ArduinoJson
    https://github.com/Athillas/arduino-CAN # custom fork is used because of usage of outdated ESP-IDF library in original code.