[env:upesy_wroom]
platform = espressif32
board = upesy_wroom
framework = arduino
monitor_encoding = utf-8
monitor_speed = 115200

lib_deps =
    https://github.com/knolleary/pubsubclient
    https://github.com/arduino-libraries/Ethernet
    https://github.com/bblanchon/ArduinoJson
    https://github.com/Athillas/arduino-CAN # custom fork is used because of usage of outdated ESP-IDF library in original code.